# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
strategyType:
enableSelector:
deploymentApiVersion: apps/v1
fullnameOverride: "production"
namespace: orchestrator-3-staging
address: 35.241.228.250.nip.io
image:
  repository: $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
  tag: latest
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry-root-orchestrator
    - name: gitlab-registry
application:
  track: latest
  tier: web
