# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
strategyType:
enableSelector:
deploymentApiVersion: apps/v1
#fullnameOverride: "production"
image:
  repository: gitlab.iotcrawler.net:4567/orchestrator/orchestrator/master
  tag: latest
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry
