# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
strategyType:
enableSelector:
deploymentApiVersion: apps/v1
fullnameOverride: "production"
image:
  repository: ${CI_APPLICATION_REPOSITORY}:$CI_APPLICATION_TAG
  tag: latest
  pullPolicy: IfNotPresent
  secrets:
    - name: gitlab-registry
