stages:
  - build
  - build-image
  - tests


build:
  stage: build
  script:
    - make install
    
build-image:
  stage: build-image
  image: gitlab.iotcrawler.net:4567/core/maven-docker-compose:latest
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - export CGO_ENABLED=1
    - systemctl status docker | grep Tasks
    - cd orchestrator && make build-image && cd ..
    - cd orchestrator && make push-image && cd ..  

tests: 
  stage: tests
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker ps
    - less /proc/meminfo
    - cd orchestrator && make start-containers && cd ..
    - docker ps
  script:
    - less /proc/meminfo
    - echo $IOTCRAWLER_RABBIT_HOST
    - cd orchestrator && make rpc-client-test  && cd ..
  after_script:
    #- cd orchestrator && make stop-containers
  