stages:
  - build
  - build-image
  - tests


build:
  stage: build
  script:
    - make install
    
build-image:
  stage: build-image
  image: gitlab.iotcrawler.net:4567/core/maven-docker-compose:latest
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker image prune
  script:
    - cd orchestrator && make build-image && cd ..
    - cd orchestrator && make push-image && cd ..  

tests: 
  stage: tests
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cd orchestrator && make start-containers && cd ..
    - cd orchestrator && docker-compose ps && cd ..
  script:
    - cd orchestrator && make rpc-client-test && cd ..
  after_script:
    - cd fiware/clients && sh make.sh compose-down && cd ..
  