stages:
  - build-codes
  - build-image
  - configure-docker
  - tests


build-codes:
  stage: build-codes
  script:
    - make install
    
build-image:
  stage: build-image
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cd orchestrator && make build-image  
    - docker push $CI_REGISTRY_IMAGE:1.0.8
    
    
configure-docker:
  stage: configure-docker
  script:
    - make install-reqs
    
tests: 
  stage: tests
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - sh make.sh test-fiware-clients
    #- make test-orchestrator