stages:
  - build-codes
  - build-image
  - tests


build-codes:
  stage: build-codes
  script:
    - make install
    
build-image:
  
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

  stage: build-image
  script:
    - cd orchestrator && make build-image  
    - echo $CI_REGISTRY_USER
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:1.0.8
    
tests: 
  stage: tests
  script:
    - make start
    - make test-orchestrator