apiVersion: v1
#kind: Deployment
kind: Pod
metadata:
  name: iotcrawler
  labels:
    app: orchestrator
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: orchestrator
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 33%
#   template:
#     metadata:
#       labels:
#         app: orchestrator
spec:
  containers:
    - name: orchestrator
      #image: gitlab.iotcrawler.net:4567/orchestrator/orchestrator:1.0.9
      image: gitlab.iotcrawler.net:4567/orchestrator/orchestrator/master:a94f166244a3e40ffd48d30882d72e0435f1e020
      #image: <CI_APPLICATION_REPOSITORY>:<CI_APPLICATION_TAG>
      ports:
        - containerPort: 3001
      env:
        - name: IOTCRAWLER_RABBIT_HOST
          value: "rabbit"
#            - name: IOTCRAWLER_REDIS_HOST
#              value: "redis"
#            - name: NGSILD_BROKER_URL
#              value: "http://djane:3000/ngsi-ld/"
#            - name: HTTP_SERVER_HOST
#              value: "orchestrator"
#            - name: HTTP_SERVER_PORT
#              value: 3001
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 2
#            periodSeconds: 2
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 2
#            periodSeconds: 2