apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotcrawler
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: <CI_APPLICATION_REPOSITORY>:<CI_APPLICATION_TAG>
          ports:
            - containerPort: 3001
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 2
#            periodSeconds: 2
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 2
#            periodSeconds: 2