version: '3'

services:
  mongo:
    image: mongo:4.0.9-xenial
    restart: always
    volumes:
      - /tmp/mongo/data/db:/data/db
    ports: 
      - "27017:27017"
    networks:
      - djanenetwork

  djane: 
    image: gitlab.iotcrawler.net:4567/core/djane:1.0.0
    depends_on: 
      - mongo
    environment:
      DB_HOST: mongo
    ports: 
      - "3000:3000"
    command: bash -c "./wait-for-it.sh mongo:27017 -t 30 -- npm run migrate && npm start"
    networks: 
      - djanenetwork

  iotbroker:
    image: fiware/iotbroker:standalone-dev
    restart: always
    command: "./iotbroker_dockerentrypoint.sh -p iotbroker_historicalagent='enabled'"
    ports: 
      - "8060:8060"
      - "8065:8065"
    networks:
      - djanenetwork

networks:
  djanenetwork: 
