apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orchestartor-ingress
spec:
  rules:
    - host: {{ .Values.gitlab.env }}.35.241.228.250.nip.io
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "orchestrator"
              servicePort: 3001
