apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orchestartor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    {{ if eq .Values.gitlab.env "orchestartor-production" }}
    - orchestartor.iotcrawler.eu
    {{ else }}
    - staging.orchestartor.iotcrawler.eu
    {{ end }}
    secretName: orchestartor-{{ .Values.gitlab.env }}-tls22
  rules:
  {{ if eq .Values.gitlab.env "orchestartor-production" }}
  - host: orchestartor.iotcrawler.eu
  {{ else }}
  - host: staging.orchestartor.iotcrawler.eu
  {{ end }}
    http:
      paths:
      - path: "/"
        backend:
          serviceName: "orchestrator"
          servicePort: 3001
