#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: orchestrator-ingress
#  labels:
#    app: {{ template "appname" . }}
#    service: orchestrator
#    track: "{{ .Values.application.track }}"
#    tier: "{{ .Values.application.tier }}"
#    release: {{ .Release.Name }}
#spec:
#  backend:
#    serviceName: orchestrator
#    servicePort: 3000
