apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: orchestartor-ingress
spec:
  rules:
    #- host: {{ .Values.gitlab.env }}.35.241.228.250.nip.io
    {{ if eq .Values.gitlab.env "orchestrator-production" }}
    - host: orchestrator.iotcrawler.eu
      {{ else }}
    - host: staging.orchestrator.iotcrawler.eu
    {{ end }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: "orchestrator"
              servicePort: 3001
