apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: {{ .Values.gitlab.env }} #release name
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
        #image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        image: "{{ .Values.image.repository }}:252fddbd23de1095b1538c0c4c2ea57030c488f1"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
          - name: "port3001"
            containerPort: 3001
          - name: "port80"
            containerPort: 80
        env:
          - name: VERSION
            value: "{{ .Values.image.tag }}"
          - name: IOTCRAWLER_RABBIT_HOST
            value: "rabbit.{{ .Release.Namespace }}"
          - name: IOTCRAWLER_REDIS_HOST
            value: "redis.{{ .Release.Namespace }}"
          - name: NGSILD_BROKER_URL
            value: "http://155.54.95.248:9090/ngsi-ld/"
            #value: "http://metadata-repository-scorpiobroker.35.241.228.250.nip.io/ngsi-ld/"
          - name: HTTP_SERVER_HOST
            value: "{{ .Values.gitlab.env }}.35.241.228.250.nip.io"
          - name: HTTP_SERVER_PORT
            value: "3001"
