apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/iotcrawler: "true"
        io.kompose.service: orchestrator
    spec:
      containers:
      - env:
        - name: HTTP_SERVER_HOST
          value: orchestrator
        - name: HTTP_SERVER_PORT
          value: "3001"
        - name: IOTCRAWLER_RABBIT_HOST
          value: rabbit
        - name: IOTCRAWLER_REDIS_HOST
          value: redis
        - name: IOT_BROKER_URL
          value: http://iotbroker:8060/ngsi10
        - name: NGSILD_BROKER_URL
          value: http://djane:3000/ngsi-ld/
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: ""
        name: orchestrator
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
