apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      imagePullSecrets:
{{ toYaml .Values.image.secrets | indent 10 }}
      containers:
      - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#      - env:
#        - name: IOTCRAWLER_RABBIT_HOST
#          value: "rabbit"  #production-auto-deploy.${repository-name}-${project-id}-production:${port}
#        - name: IOTCRAWLER_REDIS_HOST
#          value: "redis"
#        - name: NGSILD_BROKER_URL
#          value: "http://155.54.95.248:9090/ngsi-ld/"
#          #value: "http://metadata-repository-scorpiobroker.35.241.228.250.nip.io/ngsi-ld/"
#        - name: HTTP_SERVER_HOST
#          value: "http://orchestrator-orchestrator.35.241.228.250.nip.io"
#        - name: HTTP_SERVER_PORT
#          value: "80"

#containers:
#  - name: {{ .Chart.Name }}
#    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
#    imagePullPolicy: {{ .Values.image.pullPolicy }}
#    {{- if .Values.application.secretName }}
#    envFrom:
#      - secretRef:
#          name: {{ .Values.application.secretName }}
#    {{- end }}
#    ports:
#      - name: "{{ .Values.service.name }}"
#        containerPort: {{ .Values.service.internalPort }}
#    resources:
#  {{ toYaml .Values.resources | indent 12 }}
#        name: orchestrator
#        ports:
#        - containerPort: 3001
#        resources: {}
#      restartPolicy: Always
#      serviceAccountName: ""
#      volumes: null
#status: {}
