version: '3.3'
services:
  orchestrator:
    #image: localhost:5000/orchestrator:1.0.7
    image: gitlab.iotcrawler.net:4567/orchestrator/orchestrator:1.0.9
    environment:
      - IOTCRAWLER_RABBIT_HOST=rabbit
      - IOTCRAWLER_REDIS_HOST=redis
      - NGSILD_BROKER_URI=http://djane:3000/ngsi-ld/
      - IOT_BROKER_URI=http://iotbroker:8060/ngsi10
      - HTTP_SERVER_HOST=orchestrator
      - HTTP_SERVER_PORT=3001
    ports:
      - "3001:3001"
    networks:
      - iotcrawler
  djane:
    image: gitlab.iotcrawler.net:4567/core/djane:1.0.1
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - iotcrawler

  mongo:
    image: mongo
    #volumes:
    #  - $PWD/data=/data/db
    ports:
      - "27017:27017"
    networks:
      - iotcrawler
  ranking:
    #docker run --memory "300M" --memory-swap "1G" --name "ranking" --init --detach --env INDEXER_URL=http://localhost:3002 --publish-all gitlab.iotcrawler.net:4567/ranking/ranking
    image: gitlab.iotcrawler.net:4567/ranking/ranking
    #image: gitlab.iotcrawler.net:4567/ranking/ranking:5-ranking-fails-for-entities-with-only-type
    environment:
     #- INDEXER_URL=http://djane
     - INDEXER_URL=http://djane:3000
    ports:
      - "3003:3003"
    depends_on:
      - djane
    networks:
      - iotcrawler

  #  iotbroker:
#    image: fiware/iotbroker:standalone-dev
#    environment:
#      - iotbroker_historicalagent=enabled
#    ports:
#      - "8060:8060"
#      - "8065:8065"
#    networks:
#      - iotcrawler

  rabbit:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - iotcrawler

  redis:
    image: redis:4.0.7
    volumes:
      - ./config/redis-db:/data
    command: ["redis-server", "/data/redis.conf"]
    ports:
      - "6379:6379"
    networks:
      - iotcrawler

networks:
  iotcrawler:
    external:
      name: iotcrawler
