version: '3.3'
services:
  orchestrator:
    image: iotcrawler/orchestrator
    environment:
      - IOTCRAWLER_RABBIT_HOST=rabbit
      - IOTCRAWLER_REDIS_HOST=redis
      - NGSILD_BROKER_URI=http://155.54.95.248:9090/ngsi-ld/
      - IOT_BROKER_URI=http://172.17.0.1:8060/ngsi10
      - HTTP_SERVER_HOST=172.17.0.1
      - HTTP_SERVER_PORT=3001
      - HOST_HOSTNAME=host-ip
    ports:
      - "3001:3001"
    networks:
      - iotcrawler
  rabbit:
    image: rabbitmq:management
    networks:
      - iotcrawler
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:4.0.7
    volumes:
      - ./config/redis-db:/data
    command: ["redis-server", "/data/redis.conf"]
    networks:
      - iotcrawler
    ports:
      - "6379:6379"
networks:
  iotcrawler:
    external:
      name: iotcrawler
