version: '3.3'
services:
  orchestrator:
    #image: localhost:5000/orchestrator:1.0.7
    image: gitlab.iotcrawler.net:4567/orchestrator/orchestrator:1.0.8
    environment:
      - IOTCRAWLER_RABBIT_HOST=rabbit
      - IOTCRAWLER_REDIS_HOST=redis
      - NGSILD_BROKER_URI=http://ngsild-broker:3000/ngsi-ld/
      - IOT_BROKER_URI=http://iotbroker:8060/ngsi10
      - HTTP_SERVER_HOST=orchestrator
      - HTTP_SERVER_PORT=3001
    ports:
      - "3001:3001"
    networks:
      - iotcrawler
  ngsild-broker:
    image: iotcrawler/djane:1.0.0
    networks:
      - iotcrawler
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
      - $PWD/data=/data/db
    networks:
      - iotcrawler
    ports:
      - "27017:27017"
  iotbroker:
    image: fiware/iotbroker:standalone-dev
    environment:
      - iotbroker_historicalagent=enabled
    networks:
      - iotcrawler
    ports:
      - "8060:8060"
      - "8065:8065"
  rabbit:
    image: rabbitmq:management
    networks:
      - iotcrawler
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:4.0.7
    volumes:
      - ./config/redis-db:/data
    command: ["redis-server", "/data/redis.conf"]
    networks:
      - iotcrawler
    ports:
      - "6379:6379"
networks:
  iotcrawler:
    external:
      name: iotcrawler